sudo: required
dist: trusty

addons:
  apt:
    packages:
    - net-tools
    - openvpn

services:
- docker
- elasticsearch

language: python
python:
- "3.6"

cache: pip

stages:
  - test
  - name: deploy-dev
    if: branch = master
  - name: deploy-stg
    if: tag IS present


- BUILD=LINT

before_install:
- docker-compose up -d redis
- docker-compose ps

install:
- pip install -r requirements/testing.txt
- nvm install v7.4.0
- nvm use v7.4.0
- npm install

jobs:
  include:
    - stage: test
      script: BUILD=TESTS scripts/travis.sh
    - stage: test
      script: BUILD=LINT scripts/travis.sh
    - stage: deploy-dev
      script: scripts/deploy/run_deploy.sh testing
    - stage: deploy-stg
      script: scripts/deploy/run_deploy.sh staging
