sudo: required
dist: trusty

addons:
  apt:
    packages:
    - net-tools
    - openvpn

services:
- docker
- elasticsearch

language: python
python:
- "3.6"

cache: pip

stages:
  - test
  - deploy


- BUILD=LINT

before_install:
- docker-compose up -d redis
- docker-compose ps

install:
- pip install -r requirements/testing.txt
- nvm install v7.4.0
- nvm use v7.4.0
- npm install

jobs:
  include:
    - script: BUILD=TESTS scripts/travis.sh
    - script: BUILD=LINT scripts/travis.sh
    - stage: deploy
      deploy:
        - skip_cleanup: true
          provider: script
          script: scripts/deploy/run_deploy.sh testing
          on:
            branch: improve-travis
        - skip_cleanup: true
          provider: script
          script: scripts/deploy/run_deploy.sh staging
          on:
            tags: true
